debug: true
spring:
  logging:
    level: TRACE

  application:
    name: spring-4-rts
  http:
    log-request-details: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  redis:
    host: localhost
    port: 6379
